/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-122277-g78bfcf003b-20251229"
#endif /* AVUTIL_FFVERSION_H */
